build:
  image: library/node:0.10.41
  privileged: true
  commands:
    - apt-get update
    - apt-get install btrfs-tools -y
    - mkdir /img
    - dd if=/dev/zero of=/img/btrfs.img bs=1024 count=100000
    - mkfs.btrfs /img/btrfs.img
    - mkdir /mnt/btrfs
    - mount -t btrfs -o loop /img/btrfs.img /mnt/btrfs
    - npm install
    - npm test
