build:
  image: library/node:0.10.41
  privileged: true
  commands:
    - apt-get update
    - apt-get install btrfs-tools -y
    - mkdir /img
    - dd if=/dev/zero of=/img/btrfs.img bs=1024 count=100000
    - mkfs.btrfs /img/btrfs.img
    - mkdir /mnt/btrfs
    - mount -t btrfs -o loop /img/btrfs.img /mnt/btrfs
    - npm install --unsafe-perm
    - npm test

notify:
  slack:
    webhook_url: $$SLACK_RELEASES_WEBHOOK
    channel: releases
    username: drone

publish:
  npm:
    username: $$NPM_USERNAME
    password: $$NPM_PASSWORD
    email: $$NPM_EMAIL
    when:
      event: tag
