sudo: required

language: node_js

node_js:
  - "0.10"

services:
  - docker

before_install:
  - sudo apt-get install btrfs-tools -y
  - mkdir /img
  - dd if=/dev/zero of=/img/btrfs.img bs=1024 count=100000
  - mkfs.btrfs /img/btrfs.img
  - sudo mount -o loop /img/btrfs.img /mnt/btrfs
  - npm install

script:
  - npm test
