sudo: required

language: node_js

node_js:
  - "0.10"

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install btrfs-tools -y
  - sudo mkdir /img
  - sudo dd if=/dev/zero of=/img/btrfs.img bs=1024 count=100000
  - sudo mkfs.btrfs /img/btrfs.img
  - sudo mkdir /mnt/btrfs
  - sudo mount -t btrfs -o loop /img/btrfs.img /mnt/btrfs
  - sudo $(which npm) install

script:
  - sudo $(which npm) test

notifications:
  slack:
    secure: 2Wegv+LyyrKGvtpdq977tNMGiI/jT5ehLH1vNDsZzX8kH5xrK4fm4lz4WFW+6wUrzbRcl/RonHZb5qVa/CKVk+CvDLvIIYewQdGdsy4uQIyXHIk7FDxCUd2K+4O+ONk0xmKjhIBN1Ok5yBE4Kno71QujkJE82ynaUd/RL9GgxCDEv0uiUnf/HVRHClfyydMoADufZwcuoYUfvtoR8Ww7SmtQTeXau99fLqS8W/ye9UQCLBvdY40eFVD0/vmkPFtfgt+39TbQAiUtaWvEvmpbjzLmOmzmFjTjTbHpHHrq+UdLzGwKy3f+dJiDOM2QxG2Efe5eD37W+Vn28jFB5GNP4Y9Mi7nFjla2KnfZisvvAOqyVth3SbjEtpc0MEp8C0t9jbpd/+5HnC+LE0m02EQJqPduneyuQ4tUneYUXUWVvl2izRbxvHQBzdg/cUQe5RRqyMVrXU4Vdinr4zviSZmL5ySEVR9CZuBBCD4zssXySBvyv0C556kNPuLlLP7iqYMiyBQAgXiJege+pnOqUS+O7jzV2J2mkdIiHhYF7g9kdNIY7N16rqgIVuVnlGdAZJlKIb/kd6zqAir88SFq3qYLO7DOPlfctShatiVWmKNFh0InjI9lmNrIp7XgJ4ja6RdJHfh5gcBg9xRAdUNOwx3W84cWjH6LL8mOaZMHGyCGp9Q=
  email: false
